version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insait
    ports:
      - "5432:5432"

  flask-app:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/insait
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn insait.app:asgi_app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
