"""Changed answer column from varchar of 1024 length to text of unrestricted length

Revision ID: 0f55a8a23224
Revises: 4f3b456ce467
Create Date: 2024-12-20 15:37:37.918013

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f55a8a23224"
down_revision: Union[str, None] = "4f3b456ce467"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "answer",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "answer",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
